version: '3.8'

networks:
  my_custom_network:
    external: true # Indica que la red ya existe en Podman

services:
  point_of_sale_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/posdb
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - my_custom_network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=posdb
    volumes:
      - mongo-data:/data/db
      - ./db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro
    networks:
      - my_custom_network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_custom_network

volumes:
    mongo-data: { }
